version: '3.1'
services:
  database:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: stromwise
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      DB_HOST: host.docker.internal
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - "database:pgsql-server"
    restart: unless-stopped


